### ISSUE TITLE
OFN works on multiple domains, e.g. www.openfoodnetwork.org.uk and openfoodnetwork.org.uk

### ISSUE THREAD

**Issue by luisramos0** [openfoodfoundation/ofn-install#643] opened 2020-06-27 14:44 UTC
## Description
OFN works on multiple domains like https://www.openfoodnetwork.org.uk and https://openfoodnetwork.org.uk
and these domains have different user sessions/cookies which creates problem like https://github.com/openfoodfoundation/openfoodnetwork/issues/5179 (stripe).

We need to ensure each OFN instance only works on one domain: better use standard practice here and always use www.

## Expected Behavior
Any access to URLs like https://openfoodnetwork.tld/* redirect the user to https://www.openfoodnetwork.tld/*

## Actual Behaviour
User is able to browser OFN on https://openfoodnetwork.tld/* and https://www.openfoodnetwork.tld/* and login to each independently :face_with_head_bandage: 

## Steps to Reproduce
Login on  https://openfoodnetwork.org.uk
then go to https://www.openfoodnetwork.org.uk and see you are not logged in.

## Severity
bug-s3: a feature is broken but there is a workaround

**Comment by luisramos0** [comment] 2020-06-27 14:46
After this is done we can do: https://github.com/openfoodfoundation/openfoodnetwork/issues/5691

**Comment by RachL** [comment] 2020-10-19 09:11
@luisramos0 I just notice this one on FR prod. Maybe we the domain change we've removed a patch that we had or something like that. Anyway is this one a tough one to fix?

**Comment by luisramos0** [comment] 2020-10-19 09:58
I believe this is simple ofn-install change, add a redirect somewhere in a config file. I can look for the details on how to do this but maybe @Matt-Yorkley will already know how to do it.
I'd guess this is XS or S.

**Comment by Matt-Yorkley** [comment] 2021-08-19 08:08
Hmmm... this is a bit tricky. We can easily set a standardised redirect for all instances via ofn-install, but the switchover would be messy. The issue is that sessions are stored per-domain and the www subdomain is treated as a different domain by browsers. So when we implement the redirect, a lot of users would lose their sessions and get logged out. If they were part way through shopping or making a payment, it might get "lost"...

**Comment by RachL** [comment] 2021-09-07 08:40
@Matt-Yorkley do you know how much work is left to close this one?

**Comment by Matt-Yorkley** [comment] 2021-09-07 08:44
It's mostly fixed by https://github.com/openfoodfoundation/openfoodnetwork/pull/8090

We can do another step now, which is to standardise the URLs across all instances and use redirects so we don't use both the www and non-www URLs, but that we need to wait until after #8090 is in production before we can do that :+1:

**Closed** 2021-10-06 15:28 UTC
Labels: bug-s3
