### ISSUE TITLE
delayed_job daemon in OFN CA is not running

### ISSUE THREAD

**Issue by kristinalim** [openfoodfoundation/ofn-install#333] opened 2019-03-04 11:01 UTC
`delayed_job` daemon in OFN CA is not running.

## Description

This was discovered when investigating unusual behaviour in OFN CA.

Found out the following when investigating:

- `config/application.yml` in CA had a `BUGSNAG_API_KEY="..."`. This could have been the root cause of the broken deployment. The correct format is `BUGSNAG_API_KEY: "..."`. I already changed this.
- `tmp/pids/` was not symlinked to `../shared/pids/`. Not sure yet what other symlinks are broken. Meanwhile, the Unicorn PID file is in `../shared/pids/`.

I already removed `tmp/pids/delayed_job.pid` because `delayed_job` wasn't running.

There's a chance `unicorn` didn't restart properly / update to the currently installed release. If I simply run `delayed_job`, `delayed_job` could be in a different version from what `unicorn` is using.

We need to:

1. Fix any broken symlinks or configuration. A better idea of the current deployment process for this server would help keep us from making a mess.
2. Make sure `unicorn` is running the currently installed release.
3. Run the `delayed_job` daemon.

## Severity

bug-s1: a critical feature is broken: checkout, payments, signup, login

This affects different features: https://github.com/openfoodfoundation/openfoodnetwork/tree/master/app/jobs

**Comment by kristinalim** [comment] 2019-03-04 14:18
From [here](https://openfoodnetwork.slack.com/messages/DCSF21K4H/convo/CDLKH9MM0-1551590466.013000/):

> It seems that running the `post-receive` git hook command as is quite safe. The same symlinks and directories will be used. It just so happens that the OFN unicorn service is using tmp paths in `shared/`, everything else is using whatever is in `current/`.
>
> I've already checked `.git/hooks/post-receive` (what is triggered when pushing code updates to the server), `/etc/init.d/unicorn_openfoodnetwork`, and the files in `shared/` and their corresponding symlinks (if available).
>
> I was particularly concerned about messing up symlinks, but everything looks okay.

**Comment by kristinalim** [comment] 2019-03-04 14:27
Actually, in `.git/hooks/post-receive`, I'm seeing:

```
NEWREF=$(cat /dev/stdin | cut -d ' ' -f 2)`
git reset --hard $NEWREF
```

So after running the command, it seems like we will  to enter the git commit hash too.

`git status` and `git diff` show that uncommitted local changes (`db/schema.rb` and `config/database.yml`) are safe to reset. The `post-commit` script is what replaces the regular file `config/database.yml` to a symlink, and the changes to the DB schema file are a result of running `rake db:migrate`.

And `git reset --hard` [does not remove untracked files](https://stackoverflow.com/questions/4327708/git-reset-hard-head-leaves-untracked-files-behind), so `config/initializers/bugsnag.rb` and `public/assets` (symlink) would not be deleted.

**Comment by luisramos0** [comment] 2019-03-04 14:28
Hey, I think @mkllnk will be starting his working day in 7 or 8 hours from now. I think we should wait for him.
Is this server a twin of the aus instance? the deploy command is the same here:
https://github.com/openfoodfoundation/ofn-install/wiki/Current-deployment-status

We need to clarify what is the ofn-install adoption status, is it the same as AUS? maybe we need a CAN version of this issue? #271

**Comment by kristinalim** [comment] 2019-03-04 15:25
@luisramos0 I actually want to wait for @mkllnk too - that really would be safest.

@mkllnk reassigning this to you.

**Comment by tschumilas** [comment] 2019-03-04 16:05
I know you folks are on this -  and will not open any issues for the problems I'm having until we go through this plan since other things could be related.  For example -  I'm also not getting any producer notifications (notify producers in OC)  or any order confirmations when purcahses are made.   But -  will wait to see if that is all related to this issue.  THANKS SO MUCH for looking into this.  (Couldn't come at a worse time -  I've told 2 hubs we'll delay their shop opening for now because of it.  But I have a big demo with prospective new user this afternoon -  will do my best.)

**Comment by sauloperez** [comment] 2019-03-04 18:52
All these things are done in the background using Delayed Job so, none of them will work until we fix it.

**Comment by mkllnk** [comment] 2019-03-04 22:18
Thank you all for looking into this. I can confirm that the malformed application.yml was my mistake. The missing symlinks are probably a result of the very old version of ofn-install that was used to install this server.

The Canadian server was installed when we used Git post-receive hooks to deploy. But it is even older than the Australian instance. Since it is running on Ubuntu 14 it may not be safe to run a current ofn-install. I think we need to re-install it.

@tschumilas Thanks to @kristinalim's work the background jobs should all work again. That doesn't mean that everything is displaying correctly now. But if you change things that it should work and the shop should get updated and emails should get send. Can you confirm that this is the case?

**Comment by tschumilas** [comment] 2019-03-04 23:40
will do some of thie testing - but not until tomorrow now for me.  BUT -  I see a slew of  order confirmations........  in my inbox -  so for sure messages are flowing.

**Comment by mkllnk** [comment] 2019-03-07 02:38
Great, closing for now.

**Comment by tschumilas** [comment] 2019-03-15 16:07
This same issue is happening again -  I'm not sure how I re-open this issue.  @kristinalim  and @mkllnk  am mentioning you because you worked on this last time.  Maikel - i know you just made some other changes on the server -  could this be related to that?   So frustrating -  each time it has happened, its right before a demo to a user.

**Comment by mkllnk** [comment] 2019-03-17 22:43
DelayedJob seems to crash regularly. I set up some monitoring now but that revealed that the Heartbeat job isn't scheduled. Crontab itself seems to work. Ah, the `RAILS_ENV` variable isn't set.

**Comment by mkllnk** [comment] 2019-03-17 23:16
I set `RAILS_ENV` and delayed job seems to work. I will monitor it. But we really need to re-install the server because there may be other bits broken that we don't know of.

**Closed** 2019-03-17 23:17 UTC
Labels: s1

**Comment by tschumilas** [comment] 2019-03-17 23:34
Thanks @mkllnk  -  I really appreciate this.

**Comment by sauloperez** [comment] 2019-03-18 14:09
> I set RAILS_ENV and delayed job seems to work. I will monitor it. But we really need to re-install the server because there may be other bits broken that we don't know of.

Let's plan for this soon
