### ISSUE TITLE
bundler not installed after provisioning

### ISSUE THREAD

**Issue by MikeiLL** [openfoodfoundation/ofn-install#51] opened 2016-05-07 00:05 UTC
not sure why yet:

`/home/openfoodnetwork/apps/openfoodnetwork/current$ bundle exec rails server -b 0.0.0.0
The program 'bundle' is currently not installed. etc...`

**Comment by MikeiLL** [comment] 2016-05-07 01:51
I'm logged in as vagrant user, but I see .rbenv is installed at `/home/openfoodnetwork` (unicorn user).

Also noticing that in this [commit message](https://github.com/openfoodfoundation/ofn_deployment/blob/master/provision.yml) it states "Using zzet.rbenv version 2.1.6", but on line 23 it says `v0.4.0`.

I can `$ sudo -i -u openfoodnetwork`, then `gem list` returns a few gems but not many:

```
*** LOCAL GEMS ***

bigdecimal (1.2.4)
bundler (1.12.3, 1.12.2)
io-console (0.4.2)
json (1.8.1)
minitest (4.7.5)
psych (2.0.5)
rake (10.1.0)
rdoc (4.1.0)
test-unit (2.1.5.0)
```

I could try running bundle install from here, but would like to see if can make the deployment script do it.

I'm also not quite understanding why `provision.yml` and `ruby_update.yml` have duplicate `zzet.rbenv` roles. It makes sense in a way if we're using rbenv to install Ruby, but seems wet and error-prone. I need to revisit some Ansible docs. 

Curious how different the refactoring is going to be.

**Comment by MikeiLL** [comment] 2016-05-07 01:57
Is the server meant to be run directly from the CLI by unicorn user:

`$ bundle exec rails server -b 0.0.0.0
=> Booting Unicorn
=> Rails 3.2.21 application starting in development on http://0.0.0.0:3000
=> Call with -d to detach
=> Ctrl-C to shutdown server
(eval):1: warning: encountered \r in middle of line, treated as a mere space
listening on addr=0.0.0.0:3000 fd=14
worker=0 spawning...
master process ready
worker=0 spawned pid=8147
worker=0 ready`

Or do we want to run it in the CLI via unicorn like:

`$ bundle exec unicorn -E development -c config/unicorn.rb `?

**Comment by MikeiLL** [comment] 2016-05-07 23:06
Digging a little further. It looks like `bundle install app dependencies` in `roles.deploy/tasks/main.yml` is looking for `build_path`, which would, I believe be: `/home/openfoodnetwork/apps/openfoodnetwork/build`:

`app_path: "{{ unicorn_home_path }}/apps/{{ app }}"`
`build_path: "{{ app_path }}/build"`

There's not a `build` directory in:
`/home/openfoodnetwork/apps/openfoodnetwork`
Just:
```
backups  
current  
releases-old  
rollback  
rollback.sql.gz  
shared
```

**Comment by pmackay** [comment] 2016-05-25 16:45
Would you be willing to try reproducing this on the `infrastructure` branch?

**Comment by MikeiLL** [comment] 2016-05-25 20:43
I think I could do that. Would you like me to checkout the _infrastructure_ branch and try deploying to Vagrant development from there?

**Comment by enricostano** [comment] 2017-12-22 05:34
@MikeiLL I'm closing this issue since it has been too long and we still don't have a clear plan on Vagrant.

Please feel free to ping me if you want to work on it. Thanks!

**Closed by enricostano** 2017-12-22 05:34 UTC
