### ISSUE TITLE
Provision and deploy Australia's production with ofn-install

### ISSUE THREAD

**Issue by sauloperez** [openfoodfoundation/ofn-install#271] opened 2018-11-09 11:02 UTC
We need to reprovision and then deploy Australia's production server with `ofn-install`. This will require adding its configuration settings to this repo and prevent people from using it while we provision and deploy.  

We need to provision a new production server for Australia so that we provision and deploy to it with `ofn-install`. This will require:

* Provision the new machine
* Deploy to it
* Stop old server (at night when no one uses it)
* Import database dump to the new server
* Change DNS record to point to the new server
* Ditch the old server

**Comment by sauloperez** [comment] 2018-11-12 16:34
what are your thoughts on this @mkllnk ?

**Comment by mkllnk** [comment] 2018-11-14 23:08
The new staging server is running with ofn-install, plus some scripts for easy integration with Semaphore (which I would like to share soon).

Regarding the switch of the production server: It was updated less than a year ago and it works perfectly for us. I think the next time we replace the server should be when we switch to Ubuntu 18. It's a lot of work to do it without interruption.

Using ofn-install for the staging server, I had a few cases in which deployment failed. There are also 48 open issues at the moment while our current way of deployment has proven itself for years.

I know that you want to standardise all servers which is a really good idea. But I also think that there is a lot more to do to make ofn-install deploys as easy and as robust and flexible as our current deploy script. I would love to work more on this, there are just so many other priorities.

Please correct me if I'm wrong: Is the current problem that I'm the only one who understands how the server is setup and how to work with it?

**Comment by sauloperez** [comment] 2018-11-15 08:07
I really appreciate your feedback.

> Regarding the switch of the production server: It was updated less than a year ago and it works perfectly for us. I think the next time we replace the server should be when we switch to Ubuntu 18. It's a lot of work to do it without interruption.

The point is not to replace the server, the specs are fine. It's about provisioning and deploying so that it works as most of the other production servers. It doesn't need to be a new machine.

> Using ofn-install for the staging server, I had a few cases in which deployment failed. 

It'd be great if you could share them as issues so we can fix them. I haven't had any problem in a long time and haven't heard much from others. Only François had few issues which seem mostly solved.

> There are also 48 open issues at the moment while our current way of deployment has proven itself for years.

AFAIK you're the only one using that script whereas `ofn-install` is used and maintained by the rest of the team. The larger its user base the more issues it will get reported, and I'd say that it is actually good. Most of them are improvements we all will benefit from. 

> Please correct me if I'm wrong: Is the current problem that I'm the only one who understands how the server is setup and how to work with it?

That's problem number 1, I'd say. The initiative of standardizing the infrastructure/sysadmin that started back in the Australian gathering was meant to enable the global poll of sysadmins to fix any problem any production server may experience. Basically, now you are the single point of failure for at least Australia. I guess it is on you guys to decide if that is a problem or not.

Secondly, and not less important is the fact that as OFN we are trying to share the costs of running this software as a way to achieve our common goals, in which the infrastructure plays a key role. It feels pointless to me to duplicate efforts having two mechanisms of doing deploys and not leveraging the power of open source by joining efforts, even more at this point where this strategy has proven successful for OFN.

What I wonder though is, how do you provision servers then? do you use `ofn-install` in that case?

**Comment by luisramos0** [comment] 2018-11-15 10:48
yes, that's it.
the two important points are really bus factor and standardization.
- Standardization: we are becoming very aware of the cost of maintaining custom servers.
- Bus factor: ultimately this should be driven by AUS instance managers, if AUS instance managers want to have global community support with sysadmin (like reducing the bus factor on support and releases), this issue needs to be done.

@mkllnk I think this is a good opportunity to validate ofn-install. All the advantages you see in the current AUS live setup should be listed and planned to be included in ofn-install.

**Comment by mkllnk** [comment] 2018-11-15 23:36
> The point is not to replace the server, the specs are fine. It's about provisioning and deploying so that it works as most of the other production servers. It doesn't need to be a new machine.

Okay, there may be some manual tweaking required, but yes, we can do that. I would like to do it myself as I know all customisations.

> It'd be great if you could share them as issues so we can fix them.

I did when I knew what happened. But last time it just didn't move the build directory to its destination. I have no idea why. Following commands trying to build assets in an empty directory failed. Should I still create an issue even though there is no clue of what happened? I can't reproduce it.

> What I wonder though is, how do you provision servers then? do you use ofn-install in that case?

Yes, always! We always used ofn-install. But then we developed the git post-receive hook for faster, easier and more reliable deploys (not provisioning) for continuous deployment. We always had the plan to remove the duplication and make ofn-install use the same script for deploys so that it's all standardised and efficient. But before we got to it, the global community picked up ofn-install and ignored our deploy script. It seemed to me that nobody understood it, because there was no special documentation about it. But it's actually very simple. And our script has always been installed by ofn-install as well. It's already on your server. They work together.

I have been advocating to merge the two approaches, because I see a lot of value in both approaches. 

With most ofn-install developers not using the post-receive script, the harmony between ofn-install and the deploy script became untested and I became cautious about running ofn-install on a production server. I totally agree that we need to standardise to get rid of this gap.

**Comment by sauloperez** [comment] 2018-11-19 17:39
So then, how do you think we can proceed @mkllnk ?

**Comment by mkllnk** [comment] 2018-11-20 02:03
1. I upgrade Aus production so that it is ofn-install compatible again.
2. I integrate my staging deploy scripts in ofn-install.
3. We solve all issues in ofn-install. :smile: 

Sounds reasonable?

**Comment by Matt-Yorkley** [comment] 2019-07-12 11:59
#462 has been merged now, so does this mean Aus production is ready to provision?

**Comment by mkllnk** [comment] 2019-07-18 04:44
Not quite. There are a few roles that haven't been tested yet: https://github.com/openfoodfoundation/ofn-install/wiki/Australia

In addition, I would like to have ofn-install give us zero-downtime deployments as we have at the moment. #475

#467 would be nice as well but is not a blocker.

**Comment by mkllnk** [comment] 2019-07-25 05:37
I ran almost all provision roles on aus-prod, only the app is left. I also reviewed the issues and I don't think there is a critical blocker. Zero-downtime would be ace but I will just see how the current downtime is, probably under 5 seconds.

So tomorrow morning I will run a full provision and deploy of the currently installed version. The code shouldn't change. It will just be a verification of the ofn-install compatibility. If that goes well, we are ready for v2 with ofn-install!

**Comment by luisramos0** [comment] 2019-07-25 11:56
Amazing news! Thanks Maikel!

**Comment by Matt-Yorkley** [comment] 2019-07-25 13:19
Awesome! Let us know what the downtime window is

**Comment by mkllnk** [comment] 2019-07-26 00:41
Done!

Since I deployed the same version that was deployed already, I didn't experience any downtime. But we could have downtimes of over 2 minutes in future deployments. What Ansible does:

```
TASK [deploy : move build to current] 
Friday 26 July 2019  10:31:31 +1000 (0:00:02.957)       0:02:24.473 *********** 

TASK [deploy : check database status] 
Friday 26 July 2019  10:31:33 +1000 (0:00:01.547)       0:02:26.020 *********** 

TASK [deploy : load schema if it isn't loaded] 
Friday 26 July 2019  10:31:34 +1000 (0:00:01.383)       0:02:27.403 *********** 

TASK [deploy : migrate database] 
Friday 26 July 2019  10:31:34 +1000 (0:00:00.053)       0:02:27.456 *********** 

TASK [deploy : seed database] 
Friday 26 July 2019  10:31:48 +1000 (0:00:13.623)       0:02:41.080 *********** 

TASK [deploy : restart delayed job service] 
Friday 26 July 2019  10:32:05 +1000 (0:00:16.879)       0:02:57.959 *********** 

TASK [deploy : update whenever] 
Friday 26 July 2019  10:32:49 +1000 (0:00:44.283)       0:03:42.243 *********** 

RUNNING HANDLER [precompile assets] 
Friday 26 July 2019  10:32:52 +1000 (0:00:02.864)       0:03:45.107 *********** 

RUNNING HANDLER [precompile nondigest assets] 
Friday 26 July 2019  10:33:35 +1000 (0:00:43.299)       0:04:28.407 *********** 

RUNNING HANDLER [restart unicorn] 
Friday 26 July 2019  10:33:50 +1000 (0:00:15.180)       0:04:43.587 *********** 
```

The problem here is that we use handlers in a way that we have a lot happening between replacing `current` and reloading unicorn. Precompiling assets takes a long time. It should be done before we move the folder to current.

**Closed** 2019-07-26 00:41 UTC

**Comment by luisramos0** [comment] 2019-07-26 09:27
wow, can we close the epic #269 ?
