### ISSUE TITLE
[Spike] UK downtime 07/22/2019 03:57 PM UTC - 07/22/2019 04:18 PM UTC

### ISSUE THREAD

**Issue by sauloperez** [openfoodfoundation/ofn-install#477] opened 2019-07-23 08:06 UTC
UK's Happy Apps reported the following yesterday

![Screenshot from 2019-07-23 10-03-23](https://user-images.githubusercontent.com/762088/61694121-278c0000-ad31-11e9-8c61-c17e8a9bae75.png)

but Today as well and twice 

```
An Incident of severity 'CRITICAL' was opened for App: UK Uptime on 07/22/2019 11:56 PM UTC
An Incident of severity 'CRITICAL' was closed for UK Uptime on 07/23/2019 12:22 AM UTC
```

```
An Incident of severity 'CRITICAL' was opened for App: UK Uptime on 07/23/2019 06:51 AM UTC
An Incident of severity 'CRITICAL' was closed for UK Uptime on 07/23/2019 07:12 AM UTC
```

**Comment by sauloperez** [comment] 2019-07-23 08:19
I'm digging through DJ's logs and as a side note, this might too much for system to process:

```
2019-07-22T03:03:05+0000: [Worker(delayed_job host:production18 pid:26930)] Job ProductsCacheIntegrityCheckerJob (id=1874752) COMPLETED after 6.1707
2019-07-22T03:03:05+0000: [Worker(delayed_job host:production18 pid:26930)] Job ProductsCacheIntegrityCheckerJob (id=1874753) RUNNING
2019-07-22T03:03:11+0000: [Worker(delayed_job host:production18 pid:26930)] Job ProductsCacheIntegrityCheckerJob (id=1874753) COMPLETED after 5.9719
2019-07-22T03:03:11+0000: [Worker(delayed_job host:production18 pid:26930)] Job ProductsCacheIntegrityCheckerJob (id=1874754) RUNNING
2019-07-22T03:03:11+0000: [Worker(delayed_job host:production18 pid:26930)] Job ProductsCacheIntegrityCheckerJob (id=1874754) COMPLETED after 0.7199
2019-07-22T03:03:11+0000: [Worker(delayed_job host:production18 pid:26930)] Job ProductsCacheIntegrityCheckerJob (id=1874755) RUNNING
2019-07-22T03:03:12+0000: [Worker(delayed_job host:production18 pid:26930)] Job ProductsCacheIntegrityCheckerJob (id=1874755) COMPLETED after 0.5178
2019-07-22T03:03:12+0000: [Worker(delayed_job host:production18 pid:26930)] Job ProductsCacheIntegrityCheckerJob (id=1874756) RUNNING
2019-07-22T03:03:13+0000: [Worker(delayed_job host:production18 pid:26930)] Job ProductsCacheIntegrityCheckerJob (id=1874756) COMPLETED after 0.7475
2019-07-22T03:03:13+0000: [Worker(delayed_job host:production18 pid:26930)] Job ProductsCacheIntegrityCheckerJob (id=1874757) RUNNING
2019-07-22T03:03:21+0000: [Worker(delayed_job host:production18 pid:26930)] Job ProductsCacheIntegrityCheckerJob (id=1874757) COMPLETED after 8.6938
2019-07-22T03:03:21+0000: [Worker(delayed_job host:production18 pid:26930)] Job ProductsCacheIntegrityCheckerJob (id=1874758) RUNNING
2019-07-22T03:03:22+0000: [Worker(delayed_job host:production18 pid:26930)] Job ProductsCacheIntegrityCheckerJob (id=1874758) COMPLETED after 0.2090
2019-07-22T03:03:22+0000: [Worker(delayed_job host:production18 pid:26930)] Job ProductsCacheIntegrityCheckerJob (id=1874759) RUNNING
2019-07-22T03:03:22+0000: [Worker(delayed_job host:production18 pid:26930)] Job ProductsCacheIntegrityCheckerJob (id=1874759) COMPLETED after 0.2883
2019-07-22T03:03:22+0000: [Worker(delayed_job host:production18 pid:26930)] Job ProductsCacheIntegrityCheckerJob (id=1874760) RUNNING
2019-07-22T03:03:22+0000: [Worker(delayed_job host:production18 pid:26930)] Job ProductsCacheIntegrityCheckerJob (id=1874760) COMPLETED after 0.1833
2019-07-22T03:03:22+0000: [Worker(delayed_job host:production18 pid:26930)] Job ProductsCacheIntegrityCheckerJob (id=1874761) RUNNING
2019-07-22T03:03:22+0000: [Worker(delayed_job host:production18 pid:26930)] Job ProductsCacheIntegrityCheckerJob (id=1874761) COMPLETED after 0.2408
2019-07-22T03:03:22+0000: [Worker(delayed_job host:production18 pid:26930)] Job ProductsCacheIntegrityCheckerJob (id=1874762) RUNNING
2019-07-22T03:03:27+0000: [Worker(delayed_job host:production18 pid:26930)] Job ProductsCacheIntegrityCheckerJob (id=1874762) COMPLETED after 4.1522
2019-07-22T03:03:27+0000: [Worker(delayed_job host:production18 pid:26930)] Job ProductsCacheIntegrityCheckerJob (id=1874763) RUNNING
2019-07-22T03:03:27+0000: [Worker(delayed_job host:production18 pid:26930)] Job ProductsCacheIntegrityCheckerJob (id=1874763) COMPLETED after 0.6472
2019-07-22T03:03:27+0000: [Worker(delayed_job host:production18 pid:26930)] Job ProductsCacheIntegrityCheckerJob (id=1874764) RUNNING
2019-07-22T03:03:33+0000: [Worker(delayed_job host:production18 pid:26930)] Job ProductsCacheIntegrityCheckerJob (id=1874764) COMPLETED after 5.7615
2019-07-22T03:03:33+0000: [Worker(delayed_job host:production18 pid:26930)] Job ProductsCacheIntegrityCheckerJob (id=1874765) RUNNING
2019-07-22T03:03:33+0000: [Worker(delayed_job host:production18 pid:26930)] Job ProductsCacheIntegrityCheckerJob (id=1874765) COMPLETED after 0.2262
2019-07-22T03:03:33+0000: [Worker(delayed_job host:production18 pid:26930)] Job ProductsCacheIntegrityCheckerJob (id=1874766) RUNNING
2019-07-22T03:03:33+0000: [Worker(delayed_job host:production18 pid:26930)] Job ProductsCacheIntegrityCheckerJob (id=1874766) COMPLETED after 0.2175
2019-07-22T03:03:33+0000: [Worker(delayed_job host:production18 pid:26930)] Job ProductsCacheIntegrityCheckerJob (id=1874767) RUNNING
2019-07-22T03:03:34+0000: [Worker(delayed_job host:production18 pid:26930)] Job ProductsCacheIntegrityCheckerJob (id=1874767) COMPLETED after 0.2541
2019-07-22T03:03:34+0000: [Worker(delayed_job host:production18 pid:26930)] Job ProductsCacheIntegrityCheckerJob (id=1874768) RUNNING
2019-07-22T03:03:34+0000: [Worker(delayed_job host:production18 pid:26930)] Job ProductsCacheIntegrityCheckerJob (id=1874768) COMPLETED after 0.2677
2019-07-22T03:03:34+0000: [Worker(delayed_job host:production18 pid:26930)] Job ProductsCacheIntegrityCheckerJob (id=1874769) RUNNING
2019-07-22T03:03:38+0000: [Worker(delayed_job host:production18 pid:26930)] Job ProductsCacheIntegrityCheckerJob (id=1874769) COMPLETED after 3.7656
2019-07-22T03:03:38+0000: [Worker(delayed_job host:production18 pid:26930)] Job ProductsCacheIntegrityCheckerJob (id=1874770) RUNNING
2019-07-22T03:03:38+0000: [Worker(delayed_job host:production18 pid:26930)] Job ProductsCacheIntegrityCheckerJob (id=1874770) COMPLETED after 0.0694
2019-07-22T03:03:38+0000: [Worker(delayed_job host:production18 pid:26930)] Job ProductsCacheIntegrityCheckerJob (id=1874771) RUNNING
2019-07-22T03:03:38+0000: [Worker(delayed_job host:production18 pid:26930)] Job ProductsCacheIntegrityCheckerJob (id=1874771) COMPLETED after 0.3357
2019-07-22T03:03:38+0000: [Worker(delayed_job host:production18 pid:26930)] Job ProductsCacheIntegrityCheckerJob (id=1874772) RUNNING
2019-07-22T03:03:39+0000: [Worker(delayed_job host:production18 pid:26930)] Job ProductsCacheIntegrityCheckerJob (id=1874772) COMPLETED after 0.4609
2019-07-22T03:03:39+0000: [Worker(delayed_job host:production18 pid:26930)] Job ProductsCacheIntegrityCheckerJob (id=1874773) RUNNING
2019-07-22T03:03:39+0000: [Worker(delayed_job host:production18 pid:26930)] Job ProductsCacheIntegrityCheckerJob (id=1874773) COMPLETED after 0.4716
2019-07-22T03:03:39+0000: [Worker(delayed_job host:production18 pid:26930)] Job ProductsCacheIntegrityCheckerJob (id=1874774) RUNNING
2019-07-22T03:03:40+0000: [Worker(delayed_job host:production18 pid:26930)] Job ProductsCacheIntegrityCheckerJob (id=1874774) COMPLETED after 1.1563
2019-07-22T03:03:40+0000: [Worker(delayed_job host:production18 pid:26930)] Job ProductsCacheIntegrityCheckerJob (id=1874775) RUNNING
2019-07-22T03:03:41+0000: [Worker(delayed_job host:production18 pid:26930)] Job ProductsCacheIntegrityCheckerJob (id=1874775) COMPLETED after 1.1106
2019-07-22T03:03:41+0000: [Worker(delayed_job host:production18 pid:26930)] Job ProductsCacheIntegrityCheckerJob (id=1874776) RUNNING
```

**Comment by lin-d-hop** [comment] 2019-07-23 08:27
Thanks for looking into this @sauloperez!
This is obviously a critical issue, system down. I really appreciate that you've picked it up as if I'd had a notification I would have been bouncing around all stressy in the dev channel.

I wonder if there is a way that I can be notified of CRITICAL incidents in slack without being on a channel that notifies me constantly of things that I don't need to stress about.
I also wonder if that really is a good idea.....

**Comment by sauloperez** [comment] 2019-07-23 08:31
I understand your concern and we could have even a CRITICAL channel where we only report HappyApps alarms. That would solve it. However, I think it still more about taking ownership and dealing with these things. We all (myself included) have been neglecting these #ops tasks.

**Comment by sauloperez** [comment] 2019-07-23 08:44
I think I got it. HappyApps uses the `Heartbeat Job` to check the app's status every 5 minutes. I fail to understand why it reported downtime since heartbeat jobs were all completed around the time of the incident (15:50 - 16:20 UTC):

```sh
2019-07-22T15:50:03+0000: [Worker(delayed_job host:production18 pid:26930)] Job HeartbeatJob (id=1876683) RUNNING                                                                     
2019-07-22T15:50:03+0000: [Worker(delayed_job host:production18 pid:26930)] Job HeartbeatJob (id=1876683) COMPLETED after 0.0102                                                      
2019-07-22T15:50:03+0000: [Worker(delayed_job host:production18 pid:26930)] Job HeartbeatJob (id=1876682) RUNNING                                                                     
2019-07-22T15:50:03+0000: [Worker(delayed_job host:production18 pid:26930)] Job HeartbeatJob (id=1876682) COMPLETED after 0.0098                                                      
2019-07-22T15:55:09+0000: [Worker(delayed_job host:production18 pid:26930)] Job HeartbeatJob (id=1876685) RUNNING                                                                     
2019-07-22T15:55:09+0000: [Worker(delayed_job host:production18 pid:26930)] Job HeartbeatJob (id=1876685) COMPLETED after 0.0079                                                      
2019-07-22T15:55:09+0000: [Worker(delayed_job host:production18 pid:26930)] Job HeartbeatJob (id=1876687) RUNNING                                                                     
2019-07-22T15:55:09+0000: [Worker(delayed_job host:production18 pid:26930)] Job HeartbeatJob (id=1876687) COMPLETED after 0.0080                                                      
2019-07-22T16:00:11+0000: [Worker(delayed_job host:production18 pid:26930)] Job HeartbeatJob (id=1876693) RUNNING                                                                     
2019-07-22T16:00:11+0000: [Worker(delayed_job host:production18 pid:26930)] Job HeartbeatJob (id=1876693) COMPLETED after 0.0087                                                      
2019-07-22T16:00:11+0000: [Worker(delayed_job host:production18 pid:26930)] Job HeartbeatJob (id=1876696) RUNNING                                                                     
2019-07-22T16:00:11+0000: [Worker(delayed_job host:production18 pid:26930)] Job HeartbeatJob (id=1876696) COMPLETED after 0.0077                                                      
2019-07-22T16:05:08+0000: [Worker(delayed_job host:production18 pid:26930)] Job HeartbeatJob (id=1876767) RUNNING               
2019-07-22T16:05:08+0000: [Worker(delayed_job host:production18 pid:26930)] Job HeartbeatJob (id=1876767) COMPLETED after 0.0087
2019-07-22T16:05:08+0000: [Worker(delayed_job host:production18 pid:26930)] Job HeartbeatJob (id=1876768) RUNNING
2019-07-22T16:05:08+0000: [Worker(delayed_job host:production18 pid:26930)] Job HeartbeatJob (id=1876768) COMPLETED after 0.0168
2019-07-22T16:10:05+0000: [Worker(delayed_job host:production18 pid:26930)] Job HeartbeatJob (id=1876774) RUNNING
2019-07-22T16:10:05+0000: [Worker(delayed_job host:production18 pid:26930)] Job HeartbeatJob (id=1876774) COMPLETED after 0.0177
2019-07-22T16:10:10+0000: [Worker(delayed_job host:production18 pid:26930)] Job HeartbeatJob (id=1876777) RUNNING
2019-07-22T16:10:10+0000: [Worker(delayed_job host:production18 pid:26930)] Job HeartbeatJob (id=1876777) COMPLETED after 0.0108
2019-07-22T16:15:10+0000: [Worker(delayed_job host:production18 pid:26930)] Job HeartbeatJob (id=1876783) RUNNING
2019-07-22T16:15:11+0000: [Worker(delayed_job host:production18 pid:26930)] Job HeartbeatJob (id=1876783) COMPLETED after 0.0489
2019-07-22T16:15:11+0000: [Worker(delayed_job host:production18 pid:26930)] Job HeartbeatJob (id=1876785) RUNNING
2019-07-22T16:15:11+0000: [Worker(delayed_job host:production18 pid:26930)] Job HeartbeatJob (id=1876785) COMPLETED after 0.0138
2019-07-22T16:20:06+0000: [Worker(delayed_job host:production18 pid:26930)] Job HeartbeatJob (id=1876786) RUNNING
2019-07-22T16:20:06+0000: [Worker(delayed_job host:production18 pid:26930)] Job HeartbeatJob (id=1876786) COMPLETED after 0.0076
2019-07-22T16:20:06+0000: [Worker(delayed_job host:production18 pid:26930)] Job HeartbeatJob (id=1876788) RUNNING
2019-07-22T16:20:06+0000: [Worker(delayed_job host:production18 pid:26930)] Job HeartbeatJob (id=1876788) COMPLETED after 0.0100
```

**Comment by sauloperez** [comment] 2019-07-23 09:03
Datadog does report a hiccup though. Looks PostgreSQL was a bit busy (too many seq scans I'd say) 

![Screenshot from 2019-07-23 10-56-56](https://user-images.githubusercontent.com/762088/61698438-66be4f00-ad39-11e9-9df8-c2335f7ad1d6.png)
![Screenshot from 2019-07-23 10-57-54](https://user-images.githubusercontent.com/762088/61698447-6c1b9980-ad39-11e9-86d9-d73ab0c1f79c.png)

and that affected the systems load

![Screenshot from 2019-07-23 11-01-38](https://user-images.githubusercontent.com/762088/61698464-7473d480-ad39-11e9-9884-5bb7c7ec9398.png)

**Comment by kirstenalarsen** [comment] 2019-07-23 10:07
we had issues last night and on the weekend too :( I try to ignore them as long as it tell me it has recovered - which is clearly not sustainable. Not sure if @mkllnk looked into these or taking same approach! 
![image](https://user-images.githubusercontent.com/2911176/61703688-782d4880-ad85-11e9-8ed5-e4947e038249.png)

**Comment by sauloperez** [comment] 2019-07-23 14:17
I noticed too and wanted to check it after UK assuming @mkllnk would look at them as well.

**Comment by lin-d-hop** [comment] 2019-07-24 10:38
Feel free to reassign severity if you like... however now that I've had this reported twice by the same user (and other users once) I feel like this needs an s1.

**Comment by lin-d-hop** [comment] 2019-07-24 10:39
This may well have been related ing part to a Zapier glitch, that caused an over polling of the database in the past 24hrs...

Which is a very good reason to be prioritising a webhook :-)

**Comment by sauloperez** [comment] 2019-07-24 13:39
Can you give a time window when that happened @lin-d-hop . It will help correlate it with yesterday's downtime.

**Comment by sauloperez** [comment] 2019-07-24 14:03
ok, so it happened again even today. Now I see @lin-d-hop 

L'activitat de Coopdevs Treball SCCL se centra a oferir solucions de software lliure per a projectes de l'Economia Social i Solidària (ESS). Les persones que impulsen Coopdevs Treball són persones implicades des de fa anys en
projectes de l'ESS.

Els projectes de Coopdevs Treball estan orientats a facilitar i promoure àrees de l'ESS que necessiten eines tecnològiques per solucionar les seves necessitats específiques, siguin logístiques, de gestió o administratives. Coopdevs Treball creu fermament en el programari lliure, en el codi obert i en el cooperativisme obert. Raó principal per elaborar els seus projectes sempre utilitzant metodologies obertes, contribuint, al mateix temps, a l'ecosistema de codi obert.

Coopdevs Treball té experiència contrastada en les diverses fases de desenvolupament i escalat de plataformes web i en la direcció d'equips de desenvolupament d'àmbit internacional com Open Food Network i TimeOverflow i l'impacte que els productes i serveis desenvolupats tenen en comunitats locals com és el cas de Katuma.

![Screenshot from 2019-07-24 16-02-43](https://user-images.githubusercontent.com/762088/61800021-87b39c80-ae2c-11e9-8fe4-3b7cb112b2f5.png)

**Comment by sauloperez** [comment] 2019-07-24 14:52
As for the incident on the 23th at 05:59 this is what I found in the production log:

```log
Started GET "/groups" for 54.198.78.229 at 2019-07-23 17:59:00 +0000
(...)
Completed 200 OK in 54397.8ms (Views: 29054.5ms | ActiveRecord: 25341.7ms)

Started GET "/map" for 54.198.78.229 at 2019-07-23 17:59:10 +0000
(...)
Completed 200 OK in 54321.3ms (Views: 28925.7ms | ActiveRecord: 25394.3ms)
Started GET "/producers" for 54.175.53.59 at 2019-07-23 17:59:27 +0000
(...)
Completed 200 OK in 53798.4ms (Views: 28819.3ms | ActiveRecord: 24977.0ms)
```

**Comment by RachL** [comment] 2019-07-24 15:04
@sauloperez would the v2 performances improvements solve these problems? Is it worth it to work on this before UK's upgrade?

**Comment by sauloperez** [comment] 2019-07-24 15:19
That's what I want to understand.  Let's go incident by incident and propose solutions

## July 22nd

**Culprit**: `/api/products/bulk_products`. 
**Solution**:
* Investigate its impact on the DB and see potential ways to improve its DB queries 
* Refactor current pagination which loads all the pages regardless of how much you scroll. You might want to see only the first one.

## July 23rd

**Culprit**: `/producers`, `/map` and `/groups` requests
**Solution**: deploy v2 ASAP. cc @lin-d-hop we should schedule the maintenance window soon but let's have that conversation somewhere else.

## July 24th

I couldn't find a root cause yet.

**Comment by luisramos0** [comment] 2019-07-24 21:18
amazing detective work Mr. @sauloperez  👏

**Comment by mkllnk** [comment] 2019-07-24 23:34
Great work! A database timeout is new. We didn't have that in the past.

@sauloperez You said you haven't found the root cause yet. Don't you think that bad performance could be the root cause? If there are several requests taking a whole minute then other requests time out and the app appears to be down.

I haven't looked into the Aus incidents. We had similar timeouts when we were on 2 workers due to performance issues. Increasing the workers to 6 solved it but also exposed the synchronous checkout bug. So since I reduced the workers to 3 again, I'm not surprised that we experience timeouts again.

**Comment by sauloperez** [comment] 2019-07-25 07:58
> You said you haven't found the root cause yet. Don't you think that bad performance could be the root cause? If there are several requests taking a whole minute then other requests time out and the app appears to be down.

Only for the last downtime. I couldn't see any extremely long request or any misbehaving job. The point is to know which ones are causing trouble and start improving their performance.

**Comment by sauloperez** [comment] 2019-07-25 07:59
Ok, closing this as we have a plan. I don't want this to become a catch-all-UK-downtimes issue.

**Closed** 2019-07-25 08:00 UTC
Labels: bug, s1
